alerts/urls.py
from django.urls import path
from .views import alerts_root, create_alert, edit_alert, delete_confirm_alert, delete_alert

app_name = "alerts"

urlpatterns = [
    path('', alerts_root, name = "root"),
    path('create/', create_alert, name = "create"),
    path('edit/<int:alert_id>/', edit_alert, name = "edit"),
    path('delete-confirm/<int:alert_id>/', delete_confirm_alert, name = "delete-confirm"),
    path('delete/<int:alert_id>/', delete_alert, name = "delete")
]

dashboard/urls.py
from django.urls import path
from .views import dashboard_root, category_chart_data

app_name = "dashboard"

urlpatterns = [
    path('', dashboard_root, name = "root"), 
    path('category-chart/data/', category_chart_data, name = "category-chart-data")
]

mynk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


from .views import root


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', root, name="root"),
    path('accounts/', include('accounts.urls')),
    path('alerts/', include('alerts.urls')),
    path('category/', include('category.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('expense-log/', include('expense_log.urls')),
    path('reports/', include('reports.urls'))
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

alerts/models.py
from django.db import models
from django.contrib.auth.models import User

from category.models import Category

class Alert(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    limit = models.PositiveIntegerField(default = 10, verbose_name = "Limit", help_text = "Amount at which the alert should be triggered")
    alert_message = models.CharField(max_length = 64,blank = True, null = True)

    def __str__(self):
        return str(self.user)+ " | "+ str(self.category)

alerts/forms.py
from django import forms

from .models import Alert

class AlertForm(forms.ModelForm):
    class Meta:
        model = Alert
        exclude = ('user', 'alert_message')

alerts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q

from .models import Alert
from .forms import AlertForm

from category.models import Category

@login_required(login_url = 'accounts:authenticate')
def alerts_root(request):
    alerts = Alert.objects.filter(user = request.user)
    return render(request, "alerts/root.html", {"alerts": alerts})

@login_required(login_url = 'accounts:authenticate')
def create_alert(request):
    if request.method == "POST":
        alertForm = AlertForm(request.POST)
        if alertForm.is_valid():
            instance = alertForm.save(commit = False)
            instance.user = request.user

            userCheck = Q(user = request.user)
            categoryCheck = Q(category = instance.category)


            if Alert.objects.filter(userCheck & categoryCheck).exists():
                messages.warning(request, f'Alert for this category already exists')
                return redirect("alerts:root")

            
            category = instance.category
            
            if category.value < instance.limit:
                messages.warning(request, f"Alert cannot be triggered at a value greater than category limit")
                return redirect("alerts:root")

            instance.save()
            messages.warning(request, f"Alert has been created")
            return redirect("alerts:root")

    else:
        alertForm = AlertForm()
    
    alertForm.fields["category"].queryset= Category.objects.filter(user = request.user)

    return render(request, "alerts/add.html", {"alertForm": alertForm})

@login_required(login_url = 'accounts:authenticate')
def edit_alert(request, alert_id):

    try:
        alert = Alert.objects.get(id = alert_id)
        if request.user == alert.user:
            if request.method == "POST":
                alertForm = AlertForm(request.POST, instance = alert)
                if alertForm.is_valid():
                    instance = alertForm.save(commit = False)

                    category = instance.category
                    if category.value < instance.limit:
                        messages.warning(request, f"Alert cannot be triggered at a value greater than category limit")
                        return redirect("alerts:root")

                    instance.save()
                    messages.warning(request, f"Alert has been updated")
                    return redirect("alerts:root")

            else:
                alertForm = AlertForm(instance = alert)

            return render(request, "alerts/add.html", {"alertForm": alertForm})

    except:
        messages.success(request, f"Unable to fetch requested alert from your profile")
        return redirect("dashboard:root")


@login_required(login_url = 'accounts:authenticate')
def delete_confirm_alert(request, alert_id):

    try:
        alert = Alert.objects.get(id = alert_id)
        print("Got the alert")
        if request.user == alert.user:
            return render(request, "alerts/delete-confirm.html", {"alert": alert})

    except:
        messages.success(request, f"Unable to fetch requested alert from your profile")
        return redirect("dashboard:root")
    

@login_required(login_url = 'accounts:authenticate')
def delete_alert(request, alert_id):

    try:
        alert = Alert.objects.get(id = alert_id)
        if request.user == alert.user: 
            alert.delete()
            messages.success(request, f"Alert deleted from your profile")
            return redirect("dashboard:root") 
    
    except:
        messages.success(request, f"Unable to fetch requested alert from your profile")
        return redirect("dashboard:root")

    

alerts/templates/alerts/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class = "container">
		<div class="row justify-content-center">
		<div class = "col-md-8">
			<div class="card shadow">
				<div class="card-body">
					<div class="row justify-content-center">
						<div class="col-md-12">
                            <h1>Add Category</h1>
                            <hr>
							<form method="post" class = "form-group">
								{% csrf_token %}
								{{alertForm|crispy}}
                                <input type="submit" value="Continue" class="btn btn-success btn-sm mt-1 mb-1">
                                <a href="{% url 'alerts:root' %}" class="btn btn-dark btn-sm mt-1 mb-1">Back</a>
                            </form>
						</div>
					</div>
				</div>
			</div>
		</div>
		</div>
	</div>
{% endblock %}

alerts/templates/alerts/delete-confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class = "container">
		<div class="row justify-content-center">
		<div class = "col-md-8">
			<div class="card shadow">
				<div class="card-body">
					<div class="row justify-content-center">
						<div class="col-md-12">
                            <h1>Confirm Alert Deletion</h1>
                            <hr>
                            <p class="text-justify">
                                Are you sure you want to delete Alert for {{alert.category.name}} from your profile ?
                                This cannot be reverted.
                            </p>
                            <br>
                            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'alerts:delete' alert.id %}">Delete</a>
                            <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'dashboard:root' %}">Go back</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		</div>
	</div>
{% endblock %}

alerts/templates/alerts/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class = "container">
		<div class="row justify-content-center">
		<div class = "col-md-8">
			<div class="card shadow">
				<div class="card-body">
					<div class="row justify-content-center">
						<div class="col-md-12">
                            <h1>Add Category</h1>
                            <hr>
							<form method="post" class = "form-group">
								{% csrf_token %}
								{{alertForm|crispy}}
                                <input type="submit" value="Continue" class="btn btn-success btn-sm mt-1 mb-1">
                                <a href="{% url 'alerts:root' %}" class="btn btn-dark btn-sm mt-1 mb-1">Back</a>
                            </form>
						</div>
					</div>
				</div>
			</div>
		</div>
		</div>
	</div>
{% endblock %}

alerts/templates/alerts/root.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <h4>
                Alerts
                <span style="float: right;"><a class="btn btn-primary btn-sm mt-1 mb-1"
                        href="{% url 'alerts:create' %}"><i class="fas fa-plus"></i> Add</a></span>
            </h4>
            <hr>
        </div>
    </div>

    <div class="row justify-content-center">
        {% if alerts %}
        {% for alert in alerts %}
        <div class="col-md-3">
            <div class="card shadow">
                <div class="card-body">
                    <div style="float: right;">
                        <span class="ml-1">
                            <a href="{% url 'alerts:edit' alert.id %}">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill"
                                    fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                                </svg>
                            </a>
                        </span>
                        <span class="ml-1">
                            <a href="{% url 'alerts:delete-confirm' alert.id %}">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill"
                                    fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z" />
                                </svg>
                            </a>
                        </span>
                    </div>
                    <h4>{{alert.category.name}}</h4>
                    <small>{{alert.limit}} SEK</small>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <small class="text-justify">No alerts created for this profile. You can set alerts for individual categories
            under your profile by clicking the add button on the top right corner.</small>
        {% endif %}
    </div>

    {% endblock %}