category/urls.py
from django.urls import path
from .views import add_category, edit_category, delete_confirm_category, delete_category

app_name = "category"

urlpatterns = [
    path('add/', add_category, name = "add"),
    path('edit/<str:category_name>', edit_category, name = "edit"),
    path('delete-confirm/<str:category_name>', delete_confirm_category, name = "delete-confirm"),
    path('delete/<str:category_name>', delete_category, name = "delete")
]

dashboard/urls.py
from django.urls import path
from .views import dashboard_root, category_chart_data

app_name = "dashboard"

urlpatterns = [
    path('', dashboard_root, name = "root"), 
    path('category-chart/data/', category_chart_data, name = "category-chart-data")
]

mynk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


from .views import root


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', root, name="root"),
    path('accounts/', include('accounts.urls')),
    path('alerts/', include('alerts.urls')),
    path('category/', include('category.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('expense-log/', include('expense_log.urls')),
    path('reports/', include('reports.urls'))
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

class Category(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    name = models.CharField(max_length = 32, verbose_name = "Category Name")
    value = models.PositiveIntegerField(default = 0, verbose_name = "Category Limit", help_text = "Maximum spending in this category from total monthly expense")
    this_month = models.FloatField(default = 0, validators=[MinValueValidator(0)])

    def __str__(self):
        return self.name

    def calc_progress_percent(self):
        if self.value != 0:
            return (self.this_month/self.value)*100
        else:
            return 0

    def get_progress_color(self):
        value = Category.calc_progress_percent(self)
        if value < 50:
            return "bg-info"
        elif value >= 50 and value <= 70:
            return "bg-warning"
        elif value > 70:
            return "bg-danger"

category/forms.py
from django import forms
from .models import Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ('user', 'this_month')

category/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Category
from .forms import CategoryForm

@login_required(login_url = 'accounts:authenticate')
def add_category(request):
    if request.method == "POST":
        catForm = CategoryForm(request.POST)
        if catForm.is_valid():
            instance = catForm.save(commit = False)
            categories = Category.objects.filter(user = request.user)
            sum = 0
            for category in categories:
                sum += category.value
            
            sum += instance.value
            
            if(sum > request.user.profile.monthly_limit - request.user.profile.monthly_savings):
                messages.warning(request,f'Exceeding Monthly Expense limit')
                return redirect("category:add")

            instance = catForm.save(commit = False)
            instance.user = request.user
            instance.save()

            return redirect("dashboard:root")

    else:
        catForm = CategoryForm()

    return render(request, "category/add.html", {"catForm": catForm})


@login_required(login_url = 'accounts:authenticate')
def edit_category(request, category_name):

        
    userCheck = Q(user = request.user)
    categoryCheck = Q(name = category_name)


    try:
        category = Category.objects.get(userCheck & categoryCheck)    
    

    except:
        messages.success("Unable to fetch requested category in your profile")
        return redirect("dashboard:root")
    

    if request.method == "POST":
        catForm = CategoryForm(request.POST, instance = category)

        if catForm.is_valid():
            catForm.save()

            messages.success(request, f"Category Updated")
            return redirect("dashboard:root")
        
    else:
        catForm = CategoryForm(instance = category)

    return render(request, "category/edit.html", {"catForm": catForm})

    
@login_required(login_url = 'accounts:authenticate')
def delete_confirm_category(request, category_name):

    userCheck = Q(user = request.user)
    categoryCheck = Q(name = category_name)


    try:
        category = Category.objects.get(userCheck & categoryCheck)    
    

    except:
        messages.success("Unable to fetch requested category in your profile")
        return redirect("dashboard:root")
    

    return render(request, "category/delete-confirm.html", {"category": category})

    
@login_required(login_url = 'accounts:authenticate')
def delete_category(request, category_name):

    userCheck = Q(user = request.user)
    categoryCheck = Q(name = category_name)


    try:
        category = Category.objects.get(userCheck & categoryCheck)    
    

    except:
        messages.success("Unable to fetch requested category in your profile")
        return redirect("dashboard:root")

    category.delete()

    messages.success(request, f"Category deleted from your profile")
    return redirect("dashboard:root")

    

category/templates/category/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class = "container">
		<div class="row justify-content-center">
		<div class = "col-md-8">
			<div class="card shadow">
				<div class="card-body">
					<div class="row justify-content-center">
						<div class="col-md-12">
                            <h1>Add Category</h1>
                            <hr>
							<form method="post" class = "form-group">
								{% csrf_token %}
								{{catForm|crispy}}
                                <input type="submit" value="Continue" class="btn btn-success btn-sm mt-1 mb-1">
                                <a href="{% url 'dashboard:root' %}" class="btn btn-dark btn-sm mt-1 mb-1">Back</a>
                            </form>
						</div>
					</div>
				</div>
			</div>
		</div>
		</div>
	</div>
{% endblock %}

category/templates/category/delete-confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class = "container">
		<div class="row justify-content-center">
		<div class = "col-md-8">
			<div class="card shadow">
				<div class="card-body">
					<div class="row justify-content-center">
						<div class="col-md-12">
                            <h1>Confirm Category Deletion</h1>
                            <hr>
                            <p class="text-justify">
                                Are you sure you want to delete {{category.name}} from your profile ?
                                All expenses associated with this category will also be deleted. To preserve them, change their category before continuing.
                            </p>
                            <br>
                            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'category:delete' category.name %}">Delete</a>
                            <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'dashboard:root' %}">Go back</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		</div>
	</div>
{% endblock %}

category/templates/category/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class = "container">
		<div class="row justify-content-center">
		<div class = "col-md-8">
			<div class="card shadow">
				<div class="card-body">
					<div class="row justify-content-center">
						<div class="col-md-12">
                            <h1>Add Category</h1>
                            <hr>
							<form method="post" class = "form-group">
								{% csrf_token %}
								{{catForm|crispy}}
                                <input type="submit" value="Update" class="btn btn-success btn-sm mt-1 mb-1">
                                <a href="{% url 'dashboard:root' %}" class="btn btn-dark btn-sm mt-1 mb-1">Back</a>
                            </form>
						</div>
					</div>
				</div>
			</div>
		</div>
		</div>
	</div>
{% endblock %}