mynk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


from .views import root


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', root, name="root"),
    path('accounts/', include('accounts.urls')),
    path('alerts/', include('alerts.urls')),
    path('category/', include('category.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('expense-log/', include('expense_log.urls')),
    path('reports/', include('reports.urls'))
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path

from .views import reports_root,  report_details, report_chart_data, generate_report

app_name = "reports"

urlpatterns = [
    path("", reports_root, name = "root"),
    path("generate/", generate_report, name = "generate"),
    path("details/<int:report_id>/", report_details, name = "details"),
    path("chart-data/<int:report_id>/", report_chart_data, name = "category-chart-data")
]

reports/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

from category.models import Category

class Report(models.Model):

    user = models.ForeignKey(User, on_delete = models.CASCADE)
    period = models.DateField()
    total_exp = models.FloatField(default = 0, validators=[MinValueValidator(0)])
    daily_avg = models.FloatField(default = 0, validators=[MinValueValidator(0)])
    savings = models.FloatField(default = 0 , validators=[MinValueValidator(0)])

    def __str__(self):
        return str(self.user) + " | " + str(self.period)

    def get_period(self):
        month_dict = {1: 'Janaury', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June', 7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'}
        display_str = month_dict[self.period.month]
        display_str += ", " + str(self.period.year)

        return display_str

class CategorySnap(models.Model):

    report = models.ForeignKey(Report, on_delete = models.CASCADE)
    category = models.CharField(max_length = 128)
    spent = models.FloatField(default = 0, validators=[MinValueValidator(0)])

    def __str__(self):
        return str(self.report) + " | " + str(self.category)

reports/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect
from django.db.models import Sum
from django.contrib import messages

from .models import Report, CategorySnap
from category.models import Category
from expense_log.models import ExpenseLog

from datetime import date

def reports_root(request):

    reports = Report.objects.filter(user = request.user)
    return render(request, "reports/root.html", {"reports":reports})

def report_details(request, report_id):

    try:
        report = Report.objects.get(id = report_id)
        categorySnaps = CategorySnap.objects.filter(report = report)

        no_days = 0
    
        if report.period.month % 2 == 0 or report.period.month != 2 or report.period.month != 8:
            no_days = 30
        
        elif report.period.month == 8:
            no_days = 31

        elif report.period.month == 2:
            if report.period.year % 4 == 0:
                if report.period.year % 100 == 0:
                    if report.period.year % 400 == 0:
                        no_days = 29
                    else:
                        no_days = 28
                else:
                    no_days = 29
            else:
                no_days = 28

        expenseLogs = ExpenseLog.objects.filter(user = request.user, date__range=(report.period.replace(day=1), report.period.replace(day = no_days))).order_by('-date')
        return render(request,"reports/details.html", {'report': report, 'categorySnaps': categorySnaps, 'expenseLogs': expenseLogs})

    except:
        messages.warning(request,f"Unable to fetch requested report from your profile")
        return redirect("reports:root")

def report_chart_data(request, report_id):
    try:
        report = Report.objects.get(id = report_id)
        categories = CategorySnap.objects.filter(report = report)

    
        data = []
        tempBlock = []

        for snap in categories:
            tempBlock.append(snap.category)
            tempBlock.append(snap.spent)
            data.append(tempBlock)
            tempBlock = []
            
        chart = {
            'chart': {'type': 'pie', 'height': 295},
            'title': {'text': ''},
            'series': [{
                'name': 'Category Expense distribution',
                'data': data
            }]
        }

        return JsonResponse(chart)

    except:
        return JsonResponse({'message': 'Unable to fetch data'})



def generate_report(request):

    date_today = date.today()
    prev_month = 0
    prev_month_days = 0
    prev_month_year = 0

    if date_today.month != 1:
        prev_month = date_today.month - 1
    else:
        prev_month = 12

    if prev_month == 12:
        prev_month_year = date_today.year - 1
    else:
        prev_month_year = date_today.year

    if prev_month%2 == 0 or prev_month != 2 or prev_month != 8:
        prev_month_days = 30
    
    elif prev_month == 8:
        prev_month_days = 31

    elif prev_month == 2:
        if prev_month_year % 4 == 0:
            if prev_month_year % 100 == 0:
                if prev_month_year % 400 == 0:
                    prev_month_days = 29
                else:
                    prev_month_days = 28
            else:
                prev_month_days = 29
        else:
            prev_month_days = 28

    
     
    total_exp = Category.objects.aggregate(Sum('this_month'))
    daily_avg = total_exp/prev_month_days
    savings = total_exp - request.user.profile.monthly_limit + request.user.profile.monthly_savings

    report = Report.objects.create(user = request.user, period = date.today().replace(month = prev_month), total_exp = total_exp['this_month__sum'], daily_avg =  daily_avg, savings = savings)
    
    categories = Category.objects.filter(user = request.user)
    for category in categories:
        CategorySnap.objects.create(report = report, category = category.name, spent = category.this_month)
        category.this_month = 0
        category.save()

    return redirect("dashboard:root")



    

reports/templates/reports/details.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h4>
                <span>
                    <i class="fas fa-calendar-alt"></i>
                </span> 
                {{report.get_period}}
            </h4>
            <hr>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-3 col-sm-12">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card shadow">
                        <div class="card-body">
                            <center>
                                <h4>{{report.total_exp}} SEK</h4>
                                <h5>Total Expense</h5>
                            </center>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card shadow">
                        <div class="card-body">
                            <center>
                                <h4>{{report.daily_avg}} SEK</h4>
                                <h5>Daily Average</h5>
                            </center>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card shadow">
                        <div class="card-body">
                            <center>
                                <h4>{{report.savings}} SEK</h4>
                                <h5>Savings this Month</h5>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-sm-12">
            <div class="card shadow p-3 mb-5">
                <div class="card-body">
                    <h5>Expense Distribution</h5>
                    <div id="category-chart-container" style="width: 100%; height: 50%;" data-url="{% url 'reports:category-chart-data' report.id %}"></div>
                </div>
            </div>
        </div>
    </div>

    <br><br>
    <div class="row">
        <div class="col-md-12">
            <h4>Categories</h4>
        </div>
        {% for snap in categorySnaps %}
        <div class="col-lg-3 col-md-12">
            <div class="card">
                <div class="card-body">
                    <h5>{{snap.category}}</h5>
                    <span class="badge badge-primary badge-pill">{{snap.spent}} SEK</span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <br><br>
    <div class="row mb-10">
        <div class="col-md-12">
            <h4>
                Expense Log
                
            </h4>
            <hr>

            <div class="row" style="border-left: solid 2px#4bd6e5;">
                {% for expense in expenseLogs %}

                {% ifchanged expense.date %}
                <div class="col-md-12 mb-3">
                    <div class="badge badge-pill badge-dark">
                        {{expense.date|date}}
                    </div>
                </div>
                {% endifchanged %}

                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h5>
                                {% if expense.attachment %}
                                <a href="{{expense.attachment.url}}" target="_blank">
                                    <i class="fas fa-paperclip"></i> {{expense.amount}} SEK -
                                    {{expense.category}}
                                </a>
                                {% else %}
                                {{expense.amount}} SEK - {{expense.category}}
                                {% endif %}
                            </h5>
                            <p class="text-justify">{{expense.notes}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
    $.ajax({
      url: $("#category-chart-container").attr("data-url"),
      dataType: 'json',
      success: function (data) {
        Highcharts.chart("category-chart-container", data);
      }
    });
</script>

{% endblock %}

reports/templates/reports/root.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <h4>
                Reports
            </h4>
            <hr>
        </div>
    </div>

    <div class="row justify-content-center">
        {% if reports %}
        {% for report in reports %}
        <div class="col-md-3">
            <div class="card shadow">
                <div class="card-body">
                    <h4>
                        <span>
                            <i class="fas fa-calendar-alt"></i>
                        </span>
                        {{report.get_period}}
                    </h4>
                    <br>
                    <span class="badge badge-dark badge-pill">{{report.total_exp}} SEK</span>
                    <br><br>
                    <a href="{% url 'reports:details' report.id %}" class="btn btn-primary btn-sm">
                        <i class="fas fa-eye"></i> View full report
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <small class="text-justify">No reports created for this profile. Reports are automatically generated at the end of each month.</small>
        {% endif %}
    </div>

    {% endblock %}